version: '3.3'
services:
  amir_platform_ui_prod:
    restart: always
    container_name: amir_platform_ui_prod
    image: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}
    networks:
      - amir_platform_ui
    env_file: 
      - .env
    ports:
      - "3000:3000"
    deploy:
      resources:
          limits:
            cpus: 0.30
            memory: 130M
          reservations:
            cpus: 0.20
            memory: 128M

networks:
  amir_platform_ui:
    driver: bridge
